site_name: Global Tax Policy & Revenue Explorer
site_url: https://rkendev.github.io/global_tax_policy_and_revenue_explorer/
repo_url: https://github.com/rkendev/global_tax_policy_and_revenue_explorer
repo_name: rkendev/global_tax_policy_and_revenue_explorer

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - content.action.edit
    - navigation.footer
  palette:
    - scheme: default
      primary: indigo
      accent: pink

# When 'plugins' is defined, defaults aren't implied; keep 'search'
plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

nav:
  - Home: index.md
  - Changelog: changelog.md
  - ADRs:
      - "ADR-001: Initial Scope & DuckDB": docs/adr/ADR-001.md
