name: Docs

on:
  push:
    branches: [ main ]
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - "CHANGELOG.md"
  workflow_dispatch:

permissions:
  contents: write   # needed for gh-deploy to push gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install MkDocs + Material
        run: pip install mkdocs-material

      - name: Deploy to gh-pages
        run: mkdocs gh-deploy --force
